---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: emqx
      namespace: home
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.26.0
    env:
      TZ: Europe/Berlin
      ZIGBEE2MQTT_DATA: /data
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "zigbee2mqtt.${SECRET_DOMAIN}"
    securityContext:
      # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
      privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v1
        mountPath: "/data"
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/ttyACM0
    # These config values are not what is my current state of zigbee2mqtt
    # It's merely a guide for the initial start up on a fresh install
    # Everything after the first start is managed in the UI
    config:
      homeassistant: false
      device_options:
        retain: true
      permit_join: false
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://emqx"
        user: "${SECRET_MQTT_USERNAME}"
        password: "${SECRET_MQTT_PASSWORD}"
      serial:
        port: "/dev/ttyACM0"
      advanced:
        log_output:
          - console
      frontend:
        port: 8080
      experimental:
        new_api: true
    # addons:
    #   codeserver:
    #     enabled: true
    #     image:
    #       repository: codercom/code-server
    #       tag: 4.0.2
    #     workingDir: "/config"
    #     args:
    #     - --auth
    #     - "none"
    #     - --user-data-dir
    #     - "/config/.vscode"
    #     - --extensions-dir
    #     - "/config/.vscode"
    #     ingress:
    #       enabled: true
    #       annotations:
    #         kubernetes.io/ingress.class: "nginx"
    #       hosts:
    #       - host: app-config.domain.tld
    #         paths:
    #         - path: /
    #           pathType: Prefix
    #       tls:
    #       - hosts:
    #         - app-config.domain.tld
    #     volumeMounts:
    #     - name: config
    #       mountPath: /config
