---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qrowl
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/c0ffee/qrowl/qrowl
      tag: latest
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_QROWL_ADDR}"
        annotations:
          coredns.io/hostname: "qrowl.${INGRESS_DOMAIN}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 8000
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 512M
      limits:
        memory: 2048M
