---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1x8axp7vukc3vld7qhqdznsfdjx6vqpfzyrp4uf8uql7nc4rxyyesh93xws
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1x8axp7vukc3vld7qhqdznsfdjx6vqpfzyrp4uf8uql7nc4rxyyesh93xws
