---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    podAnnotations:
      configmap.reloader.stakater.com/reload: mosquitto-config
      secret.reloader.stakater.com/reload: mosquitto-secrets

    image:
      repository: eclipse-mosquitto
      tag: 2.0.15

    # initContainers:
    #   copy-config:
    #     image: eclipse-mosquitto:2.0.15@sha256:29c92f9144d4e65f7e647694d4b6aa7f0ac6a995bd102251ea05f7edf258ad20
    #     command:
    #       - "/bin/sh"
    #       - -c
    #     args:
    #       - cp /data/mosquitto_secrets/* /data/external_config/ && mosquitto_passwd -U /data/external_config/mosquitto_pwd
    #     volumeMounts:
    #       - name: mosquitto-secrets
    #         mountPath: /data/mosquitto_secrets
    #       - name: external-config
    #         mountPath: /data/external_config

    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_MOSQUITTO_ADDR}"
        annotations:
          coredns.io/hostname: "mqtt.${INGRESS_DOMAIN}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: false
          mqtt:
            enabled: true
            port: 1883

    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data
      mosquitto-config:
        enabled: true
        type: configMap
        name: mosquitto-config
        mountPath: /mosquitto/config/mosquitto.conf
        subPath: mosquitto.conf
      # mosquitto-secrets:
      #   enabled: true
      #   type: secret
      #   name: mosquitto-secrets
      #   mountPath: "-"
      external-config:
        enabled: true
        type: emptyDir
        mountPath: /mosquitto/external_config

    resources:
      requests:
        cpu: 15m
        memory: 64M
      limits:
        memory: 124M
