---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  uninstall:
    keepHistory: false
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2023.3.3
    env:
      TZ: "Europe/Berlin"
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${SVC_HA_ADDR}"
        annotations:
          coredns.io/hostname: "ha.${INGRESS_DOMAIN}"
        externalTrafficPolicy: Local
        ports:
          http:
            enabled: true
            port: 8123
          sonos:
            enabled: true
            port: 1400
            protocol: TCP
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: true
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
        mountPath: "/config"
    resources:
      requests:
        cpu: 100m
        memory: 512M
      limits:
        memory: 2048M
