---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telegraf
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com
      chart: telegraf 
      version: 1.8.14
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      INFLUX_TOKEN: "${SECRET_INFLUX_TOKEN}"
    config:
      outputs:
        - influxdb_v2:
            urls:
              - "http://influxdb-influxdb2:80"
            token: "${SECRET_INFLUX_TOKEN}"
            organization: "schunet"
            bucket: "sensors/autogen"
            user_agent: "telegraf"
      inputs:
        - mqtt_consumer:
            servers: "emqx:1883"
            data_format: json 
            topics:
              - "zigbee2mqtt/+"
              - "tele/+/SENSOR"
            client_id: "telegraf-zigbee2mqtt"
            username: "${SECRET_MQTT_USERNAME}"
            password: "${SECRET_MQTT_PASSWORD}" 
