---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.22.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      enabled: true
      ## If true will use an existing PVC instead of creating one
      useExisting: true
      ## Name of existing PVC to be used in the influx deployment
      name: grafana-config-v1
    adminUser: admin
    adminPassword: "${SECRET_GRAFANA_PASSWORD}"
