---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.33.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      enabled: true
      existingClaim: grafana-config-v1
    adminUser: admin
    adminPassword: "${SECRET_GRAFANA_PASSWORD}"
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: influxdb
            type: influxdb
            access: proxy
            isDefault: true
            url: http://influxdb-influxdb2:80
            database: sensors
            jsonData:
              httpMode: GET
              httpHeaderName1: 'Authorization'
            secureJsonData:
              httpHeaderValue1: 'Token ${SECRET_INFLUX_GRAFANA_TOKEN}'
            #jsonData:
            #  version: Flux
            #  organization: schunet
            #  defaultBucket: bucket
            #secureJsonData:
            #  token: token
