# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mz8rj3MRxeU8kmi2JAzTDXc=,iv:Tir6ehO+1tgGydeorZ41hebdB9aaMO90qCFgkm7rv0g=,tag:WU4qDbLAak+LAkw+Y349SA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: null
    SECRET_EMQX_ADMIN_PASSWORD: ENC[AES256_GCM,data:vXcm76xMOiSZMBYvSFY=,iv:vN/k3uG15ICWtLE9KdgBT807z6xEnP03J57GhyYWmXQ=,tag:p3pySPN4x1PrGQpm/BHK4g==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:5G4GBg==,iv:Ld5TsEHvobe1JxLOCgvCO8x1moOYCrNdcp2HcaSE7Ko=,tag:uOn2vxHcvc++IfQiB1yhnA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:Ie6ByPH5VAPFQGgF/Pw=,iv:IXq7s9Y92j+rBJe0pWXKYP1OdlgbaIyeDUXwzMMeeH8=,tag:erx9fumgKcJxASv5+5cAZg==,type:str]
    SECRET_INFLUX_PASSWORD: ENC[AES256_GCM,data:ZW8iJzl5X5v0jGkNiAI=,iv:JrD7oAndSAFAOuxxt50MCpMjZtjYE0rsycIqt+ORczE=,tag:akieVgn4lqVPV3l0QqLzsg==,type:str]
    SECRET_INFLUX_TOKEN: ENC[AES256_GCM,data:WugGHZJwV1FWRWlbfyzvbrfvM2VliXeBZ8ai3ttG3/PZxoU0dwO9O1p+2Xz1fP5dimOMVo5hWCG+CpCABahIsjzNErX+Ls/3LeHpOMZ9A7MVJzJ0qBtzAA==,iv:ZCKtCVqKOA/xc39ajvGfacom1sTkSeWAR7R5W1csMOk=,tag:a7Q5PWyfOo53/Ot088EFAQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:ac5CZVZD4+rtDy50V/g=,iv:sCe27gY879gYVedWe2JmXIlCIXxNlUcVzUcImSVkLY4=,tag:qW8G93IQFIKNZj6gkSHBAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x8axp7vukc3vld7qhqdznsfdjx6vqpfzyrp4uf8uql7nc4rxyyesh93xws
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPeWt5aitvUG9xSmVwQjQ5
            WWM5T21kRERXV0VDcVQvU2lXODR1VUFvRUY4CnBJTnAzZ0Iybno0QUZWdWZ6a01r
            eDA1SXBtOFdKUTJpWE9YUWYraEo0ajgKLS0tIHdWd2REakhxeXVtNDR6YkErMldx
            OG55am1NOXdOMTVvbjdRbnJFbWFlTVEKtpzug2oBlqEqk2rJkXALAjj3n5RE5cFl
            f54/yS9XiNpWaRs4B5Yz6wni3lA0ks+e0aaIBXJI61IrwbmmKL7JcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-27T21:01:03Z"
    mac: ENC[AES256_GCM,data:Pu21em0PdL8Ab1Yz3pMYnplg3eIzSJYJCKAOzLG8NsiXmLV5PEDt8LqtN15UkAQ+RQIy8jz7Pm83z11yoV+X5cjqac1QiTBVAguRkA6d5ZzV0RlBqeJexujitwbF+FLjPMBkdix1qdF8qK8Pd1JugGkIjLlNDZXHlZtgxFymofQ=,iv:SRu8YUeD4B6WrrPetySSe0pxHAn5GfHXeZO4kK118Yw=,tag:ctM6Rw3EeX3c6F13e0meAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
