---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-config-v1
  namespace: home
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: longhorn
